# Generated by Django 5.1.1 on 2024-09-22 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom Abonnée')),
                ('tel', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('tarif', models.FloatField(verbose_name='Tarif')),
            ],
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compteur', models.IntegerField(verbose_name='Numéro du compteur')),
                ('abonnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compteurs', to='Factures.abonnee')),
            ],
        ),
        migrations.CreateModel(
            name='Releves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateTimeField(verbose_name='Date relevé')),
                ('index_avant', models.FloatField(verbose_name='Index avant')),
                ('index_actuelle', models.FloatField(verbose_name='Index actuelle')),
                ('consommation', models.FloatField(null=True, verbose_name='Consommation')),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='Factures.compteur')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateField(verbose_name='Date facture')),
                ('periode', models.CharField(max_length=30, verbose_name='Période')),
                ('montant_total', models.FloatField(verbose_name='Net à payer')),
                ('date_echeance', models.DateField(verbose_name='Date échance')),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='Factures.releves')),
            ],
        ),
    ]
